export default {
    login: "akshaymarch7",
    id: 12824231,
    node_id: "MDQ6VXNlcjEyODI0MjMx",
    avatar_url: "https://avatars.githubusercontent.com/u/12824231?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/akshaymarch7",
    html_url: "https://github.com/akshaymarch7",
    followers_url: "https://api.github.com/users/akshaymarch7/followers",
    following_url: "https://api.github.com/users/akshaymarch7/following{/other_user}",
    gists_url: "https://api.github.com/users/akshaymarch7/gists{/gist_id}",
    starred_url: "https://api.github.com/users/akshaymarch7/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/akshaymarch7/subscriptions",
    organizations_url: "https://api.github.com/users/akshaymarch7/orgs",
    repos_url: "https://api.github.com/users/akshaymarch7/repos",
    events_url: "https://api.github.com/users/akshaymarch7/events{/privacy}",
    received_events_url: "https://api.github.com/users/akshaymarch7/received_events",
    type: "User",
    site_admin: false,
    name: "Akshay Saini",
    company: "@uber ",
    blog: "akshaysaini.in",
    location: "India",
    email: null,
    hireable: true,
    bio: "May the code be with you. Amen.",
    twitter_username: null,
    public_repos: 6,
    public_gists: 0,
    followers: 688,
    following: 0,
    created_at: "2015-06-10T04:36:48Z",
    updated_at: "2021-08-28T06:02:29Z",
};
